version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartranking-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - 15672:15672
      - 25672:25672
    networks:
      - app-smartranking
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

networks:
  app-smartranking:
    driver: bridge

volumes:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local
